project_id = "hxwyzwfsadsykitwaszs"

[functions.parse-products]
verify_jwt = false

[functions.create-auth-user]
verify_jwt = false

[functions.security-email-notifications]
verify_jwt = false

[functions.weekly-security-report]
verify_jwt = false

[functions.get-ip-location]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false
