// Curated theme gallery — multiple visual themes per industry. Each
// theme carries a hero image (Unsplash CDN, stable IDs — no /random),
// a full HSL palette, emoji glyph, seed categories, sample products,
// and a default welcome line.
//
// To add a new theme: drop a new entry. The screen renders all entries
// grouped by `industry`. Image URLs use Unsplash's signed CDN so they
// render offline-cached after the first load.

export interface BusinessTheme {
  id: string;
  industry: "retail" | "restaurant" | "pharmacy" | "salon" | "auto" | "services" | "supermarket" | "fashion" | "electronics" | "gym";
  name: string;
  tagline: string;
  emoji: string;
  hero: string;                // Unsplash CDN URL
  palette: {
    primary: string;           // HSL "H S% L%"
    accent: string;
    bg: string;
    foreground: string;
  };
  pos_layout: "classic" | "grid" | "restaurant" | "quick" | "dual";
  features: string[];
  seed_categories: string[];
  seed_products?: Array<{ name: string; price: number; category: string }>;
  welcome_ar: string;
  welcome_en: string;
}

const u = (id: string) =>
  `https://images.unsplash.com/${id}?w=900&auto=format&fit=crop&q=70`;

export const BUSINESS_THEMES: BusinessTheme[] = [
  // ====================== RESTAURANT (4) ======================
  {
    id: "resto-classic",
    industry: "restaurant",
    name: "مطعم كلاسيك",
    tagline: "أبيض + ذهبي — راقي ومريح للعين",
    emoji: "🍽️",
    hero: u("photo-1517248135467-4c7edcad34c4"),
    palette: { primary: "32 65% 42%", accent: "39 70% 55%", bg: "39 30% 96%", foreground: "30 25% 15%" },
    pos_layout: "restaurant",
    features: ["طاولات + Floor Plan", "KDS للمطبخ", "Split Bill", "حجوزات"],
    seed_categories: ["مقبلات", "أطباق رئيسية", "حلويات", "مشروبات"],
    seed_products: [
      { name: "كباب لحم", price: 180, category: "أطباق رئيسية" },
      { name: "شيش طاووق", price: 150, category: "أطباق رئيسية" },
      { name: "حمص", price: 35, category: "مقبلات" },
      { name: "أم علي", price: 60, category: "حلويات" },
    ],
    welcome_ar: "أهلاً وسهلاً — تفضّل اطلب",
    welcome_en: "Welcome — please order",
  },
  {
    id: "resto-darkluxe",
    industry: "restaurant",
    name: "مطعم فاخر — ليلي",
    tagline: "أسود + ذهبي — للمطاعم الراقية والفاخرة",
    emoji: "🥂",
    hero: u("photo-1414235077428-338989a2e8c0"),
    palette: { primary: "45 85% 55%", accent: "0 0% 95%", bg: "0 0% 8%", foreground: "0 0% 95%" },
    pos_layout: "restaurant",
    features: ["قائمة بصور احترافية", "تخصيص طلبات", "نقاط VIP", "تكامل التوصيل"],
    seed_categories: ["Starters", "Mains", "Desserts", "Wine", "Cocktails"],
    welcome_ar: "تجربة طهي استثنائية",
    welcome_en: "An exceptional dining experience",
  },
  {
    id: "resto-shawarma",
    industry: "restaurant",
    name: "مشاوي وشاورما",
    tagline: "أحمر + أسود — يفتح النفس",
    emoji: "🥙",
    hero: u("photo-1565299624946-b28f40a0ae38"),
    palette: { primary: "0 84% 50%", accent: "30 80% 50%", bg: "30 20% 96%", foreground: "0 30% 15%" },
    pos_layout: "quick",
    features: ["شاشة سريعة", "تيك أواي", "دلڤري", "WhatsApp تلقائي"],
    seed_categories: ["شاورما", "مشاوي", "كباب", "مقبلات", "مشروبات"],
    seed_products: [
      { name: "شاورما لحمة", price: 85, category: "شاورما" },
      { name: "شاورما فراخ", price: 70, category: "شاورما" },
      { name: "كباب حلة", price: 220, category: "مشاوي" },
    ],
    welcome_ar: "أحلى شاورما في المنطقة",
    welcome_en: "Best shawarma in town",
  },
  {
    id: "resto-pizza",
    industry: "restaurant",
    name: "بيتزا وباستا",
    tagline: "أحمر + أبيض إيطالي",
    emoji: "🍕",
    hero: u("photo-1513104890138-7c749659a591"),
    palette: { primary: "0 75% 45%", accent: "120 50% 35%", bg: "30 30% 97%", foreground: "0 50% 15%" },
    pos_layout: "restaurant",
    features: ["تخصيص العجينة والإضافات", "Combo Builder", "تتبع التوصيل"],
    seed_categories: ["بيتزا", "باستا", "سلطات", "حلويات", "مشروبات"],
    welcome_ar: "Pizza freshly made for you",
    welcome_en: "Pizza freshly made for you",
  },

  // ====================== COFFEE / CAFE (3) ======================
  {
    id: "coffee-warm",
    industry: "restaurant",
    name: "كافيه دافئ",
    tagline: "بني + بيج — جو هاديء",
    emoji: "☕",
    hero: u("photo-1495474472287-4d71bcdd2085"),
    palette: { primary: "25 47% 30%", accent: "35 60% 55%", bg: "35 25% 95%", foreground: "25 30% 18%" },
    pos_layout: "quick",
    features: ["أزرار سريعة", "تخصيص (سكر/حليب/إكسترا)", "بطاقة ولاء"],
    seed_categories: ["قهوة ساخنة", "قهوة باردة", "شاي", "كيك", "حلويات"],
    seed_products: [
      { name: "إسبريسو", price: 35, category: "قهوة ساخنة" },
      { name: "كابتشينو", price: 45, category: "قهوة ساخنة" },
      { name: "آيس لاتيه", price: 55, category: "قهوة باردة" },
      { name: "تشيز كيك", price: 65, category: "كيك" },
    ],
    welcome_ar: "صباح الفل ☕",
    welcome_en: "Good morning ☕",
  },
  {
    id: "coffee-modern",
    industry: "restaurant",
    name: "Specialty Coffee — حداثي",
    tagline: "أخضر زيتي + كريمي — Third-wave coffee",
    emoji: "🫘",
    hero: u("photo-1442512595331-e89e73853f31"),
    palette: { primary: "130 25% 25%", accent: "35 40% 65%", bg: "40 25% 96%", foreground: "130 25% 12%" },
    pos_layout: "quick",
    features: ["Roast notes per cup", "Brewing methods", "Beans subscription"],
    seed_categories: ["Pour Over", "Espresso bar", "Cold brew", "Pastries", "Beans"],
    welcome_ar: "نختار حبتنا بإيدنا",
    welcome_en: "Single-origin, freshly roasted",
  },
  {
    id: "coffee-juice",
    industry: "restaurant",
    name: "عصائر وآيس كريم",
    tagline: "ألوان فاكهة — منعش ومرح",
    emoji: "🍹",
    hero: u("photo-1546173159-315724a31696"),
    palette: { primary: "340 80% 55%", accent: "45 95% 55%", bg: "55 50% 96%", foreground: "340 50% 15%" },
    pos_layout: "quick",
    features: ["كومبو فواكه", "Add-ons", "تخصيص حلاوة"],
    seed_categories: ["عصائر طبيعية", "ميلك شيك", "آيس كريم", "كوكتيلات"],
    welcome_ar: "اخلط واصنع بنفسك 🥭",
    welcome_en: "Freshly squeezed, just for you",
  },

  // ====================== RETAIL — FASHION (3) ======================
  {
    id: "fashion-elegant",
    industry: "fashion",
    name: "بوتيك راقي",
    tagline: "وردي عتيق + ذهبي — للأزياء النسائية",
    emoji: "👗",
    hero: u("photo-1490481651871-ab68de25d43d"),
    palette: { primary: "340 35% 40%", accent: "30 50% 65%", bg: "30 25% 97%", foreground: "340 30% 15%" },
    pos_layout: "grid",
    features: ["متغيرات (مقاس + لون)", "Lookbook في المتجر", "ولاء VIP"],
    seed_categories: ["فساتين", "بلوزات", "بناطيل", "أحذية", "إكسسوارات", "حقائب"],
    welcome_ar: "أناقتك تختلف",
    welcome_en: "Where elegance lives",
  },
  {
    id: "fashion-streetwear",
    industry: "fashion",
    name: "Streetwear — شبابي",
    tagline: "أسود + أصفر فاقع — جرأة وتميز",
    emoji: "🧢",
    hero: u("photo-1441986300917-64674bd600d8"),
    palette: { primary: "45 100% 55%", accent: "0 0% 10%", bg: "0 0% 6%", foreground: "0 0% 95%" },
    pos_layout: "grid",
    features: ["Drops محدودة", "Pre-orders", "Hype rewards"],
    seed_categories: ["Hoodies", "T-shirts", "Sneakers", "Caps", "Accessories"],
    welcome_ar: "أنت اللي تحدد الترند",
    welcome_en: "Set the trend",
  },
  {
    id: "fashion-kids",
    industry: "fashion",
    name: "ملابس أطفال",
    tagline: "أزرق سماوي + وردي — مرح وطفولي",
    emoji: "🧸",
    hero: u("photo-1503944583220-79d8926ad5e2"),
    palette: { primary: "200 80% 55%", accent: "340 80% 70%", bg: "200 40% 97%", foreground: "200 50% 20%" },
    pos_layout: "grid",
    features: ["مقاسات بالعمر", "مجموعات هدايا", "بطاقات تهنئة"],
    seed_categories: ["ولاد", "بنات", "بيبي", "أحذية", "ألعاب"],
    welcome_ar: "أطفالك يستاهلوا الأحسن 🧸",
    welcome_en: "Made for little explorers",
  },

  // ====================== SUPERMARKET / GROCERY (2) ======================
  {
    id: "super-bright",
    industry: "supermarket",
    name: "سوبر ماركت مشرق",
    tagline: "أخضر + أصفر — انتعاش وثقة",
    emoji: "🛒",
    hero: u("photo-1542838132-92c53300491e"),
    palette: { primary: "140 65% 35%", accent: "45 90% 55%", bg: "0 0% 98%", foreground: "140 30% 15%" },
    pos_layout: "grid",
    features: ["باركود سريع", "ورديات X/Z", "تنبيهات الصلاحية", "موردين متعددين"],
    seed_categories: ["خضار وفاكهة", "ألبان", "لحوم", "مشروبات", "منظفات", "مخبوزات", "مجمدات"],
    welcome_ar: "كل ما تحتاجه في مكان واحد",
    welcome_en: "Fresh, every day",
  },
  {
    id: "super-mini",
    industry: "supermarket",
    name: "ميني ماركت",
    tagline: "برتقالي طازج — للمحلات الصغيرة السريعة",
    emoji: "🏪",
    hero: u("photo-1604719312566-8912e9227c6a"),
    palette: { primary: "20 90% 50%", accent: "200 75% 45%", bg: "30 20% 97%", foreground: "20 60% 15%" },
    pos_layout: "grid",
    features: ["نقطة بيع سريعة", "توصيل لقريب", "عميل دائم"],
    seed_categories: ["مشروبات", "سناكس", "علب وأكياس", "سجاير", "خبز", "حلويات"],
    welcome_ar: "كل حاجة وأنت ماشي",
    welcome_en: "Grab & go",
  },

  // ====================== ELECTRONICS (2) ======================
  {
    id: "elec-tech",
    industry: "electronics",
    name: "محل إلكترونيات — تكنولوجي",
    tagline: "أزرق غامق + سماوي — تكنولوجي ومحترف",
    emoji: "📱",
    hero: u("photo-1550009158-9ebf69173e03"),
    palette: { primary: "220 80% 35%", accent: "200 95% 55%", bg: "220 25% 97%", foreground: "220 50% 12%" },
    pos_layout: "classic",
    features: ["IMEI / Serial tracking", "ضمان وتاريخ تركيب", "إصلاحات Job Cards", "ملحقات Bundles"],
    seed_categories: ["موبايلات", "لابتوبات", "إكسسوارات", "شواحن", "سماعات", "ساعات"],
    seed_products: [
      { name: "iPhone 15 Pro 256GB", price: 65000, category: "موبايلات" },
      { name: "AirPods Pro", price: 7800, category: "سماعات" },
      { name: "Charger USB-C 20W", price: 350, category: "شواحن" },
    ],
    welcome_ar: "التكنولوجيا في خدمتك",
    welcome_en: "Tech for everyone",
  },
  {
    id: "elec-gadget",
    industry: "electronics",
    name: "Gadgets & Gaming",
    tagline: "بنفسجي + نيون — قَيمنق وعصرية",
    emoji: "🎮",
    hero: u("photo-1542751371-adc38448a05e"),
    palette: { primary: "270 75% 50%", accent: "180 95% 50%", bg: "270 25% 10%", foreground: "270 20% 95%" },
    pos_layout: "grid",
    features: ["Pre-orders للألعاب", "Trade-in", "اشتراكات", "ضمان ممتد"],
    seed_categories: ["Consoles", "Games", "PC parts", "Streaming gear", "Merch"],
    welcome_ar: "Level Up 🎮",
    welcome_en: "Level Up 🎮",
  },

  // ====================== PHARMACY (2) ======================
  {
    id: "pharma-clean",
    industry: "pharmacy",
    name: "صيدلية احترافية",
    tagline: "أزرق طبي + أبيض — نظافة وثقة",
    emoji: "💊",
    hero: u("photo-1576091160399-112ba8d25d1d"),
    palette: { primary: "200 85% 40%", accent: "165 75% 40%", bg: "200 30% 97%", foreground: "200 60% 15%" },
    pos_layout: "classic",
    features: ["تعارض الأدوية تلقائي", "تواريخ صلاحية", "Batch tracking", "روشتات + تأمين"],
    seed_categories: ["أدوية بوصفة", "أدوية OTC", "فيتامينات", "أمومة وطفل", "تجميل ورعاية", "مستلزمات طبية"],
    welcome_ar: "صحتك أمانة عندنا",
    welcome_en: "Your health, our priority",
  },
  {
    id: "pharma-natural",
    industry: "pharmacy",
    name: "صيدلية طبيعية / أعشاب",
    tagline: "أخضر زيتوني — طبيعي وعضوي",
    emoji: "🌿",
    hero: u("photo-1471864190281-a93a3070b6de"),
    palette: { primary: "140 40% 30%", accent: "65 50% 45%", bg: "60 30% 97%", foreground: "140 40% 12%" },
    pos_layout: "classic",
    features: ["مكونات طبيعية", "نصائح أعشاب", "اشتراك شهري"],
    seed_categories: ["أعشاب طبية", "زيوت طبيعية", "فيتامينات نباتية", "بشرة وعناية", "شاي"],
    welcome_ar: "كل اللي طبيعي بين إيديك 🌿",
    welcome_en: "Nature's pharmacy",
  },

  // ====================== SALON / BEAUTY (3) ======================
  {
    id: "salon-rose",
    industry: "salon",
    name: "صالون نسائي راقي",
    tagline: "وردي + ذهبي وردي — أنوثة وفخامة",
    emoji: "💇‍♀️",
    hero: u("photo-1560066984-138dadb4c035"),
    palette: { primary: "340 70% 55%", accent: "30 60% 65%", bg: "340 25% 97%", foreground: "340 50% 18%" },
    pos_layout: "classic",
    features: ["حجوزات بالساعة", "عمولة موظف لكل خدمة", "باقات شهرية", "تذكير WhatsApp"],
    seed_categories: ["قص شعر", "صبغ وهايلايت", "كيراتين", "مكياج", "بشرة", "أظافر", "مساج"],
    welcome_ar: "اطلعي كلها أنوثة ✨",
    welcome_en: "Reveal your best",
  },
  {
    id: "salon-barber",
    industry: "salon",
    name: "حلاق رجالي — Barbershop",
    tagline: "أسود + بني خشب — كلاسيكي رجالي",
    emoji: "💈",
    hero: u("photo-1503951914875-452162b0f3f1"),
    palette: { primary: "0 0% 12%", accent: "20 40% 45%", bg: "30 15% 95%", foreground: "0 0% 10%" },
    pos_layout: "classic",
    features: ["حجز فوري", "قائمة الانتظار", "ذكر آخر تسريحة لكل عميل"],
    seed_categories: ["قص شعر", "حلاقة دقن", "تهذيب", "مساج فروة", "صبغة"],
    welcome_ar: "زبون من غير ميعاد؟ خد دور",
    welcome_en: "Walk in, look sharp",
  },
  {
    id: "salon-spa",
    industry: "salon",
    name: "Spa & Wellness",
    tagline: "أخضر مائي هاديء — استرخاء كامل",
    emoji: "🧖‍♀️",
    hero: u("photo-1540555700478-4be289fbecef"),
    palette: { primary: "175 35% 35%", accent: "150 30% 55%", bg: "175 25% 96%", foreground: "175 50% 12%" },
    pos_layout: "classic",
    features: ["باقات شهرية", "غرف متعددة", "تحجير علاجي", "بطاقات هدايا"],
    seed_categories: ["مساج", "ساونا", "حمام مغربي", "بشرة عميقة", "علاجات"],
    welcome_ar: "خد نفسك من الدنيا 🍃",
    welcome_en: "Pause. Breathe. Restore.",
  },

  // ====================== AUTO / WORKSHOP (2) ======================
  {
    id: "auto-pro",
    industry: "auto",
    name: "ورشة سيارات احترافية",
    tagline: "أزرق صناعي + برتقالي تحذيري",
    emoji: "🔧",
    hero: u("photo-1486006920555-c77dcf18193c"),
    palette: { primary: "210 80% 35%", accent: "25 90% 55%", bg: "210 15% 96%", foreground: "210 40% 12%" },
    pos_layout: "dual",
    features: ["Job Cards", "Decode VIN تلقائي", "قطع غيار + بدائل", "Estimate قبل الإصلاح"],
    seed_categories: ["زيوت", "فلاتر", "إطارات", "بطاريات", "فرامل", "عمالة", "صيانة"],
    welcome_ar: "نفهم في عربيتك أكتر منك",
    welcome_en: "Drive safe, drive smart",
  },
  {
    id: "auto-luxe",
    industry: "auto",
    name: "Detailing & Premium",
    tagline: "أسود فحمي + ذهبي — للعربيات الفاخرة",
    emoji: "🚗",
    hero: u("photo-1583121274602-3e2820c69888"),
    palette: { primary: "0 0% 8%", accent: "45 80% 55%", bg: "0 0% 12%", foreground: "45 20% 95%" },
    pos_layout: "dual",
    features: ["باقات تفصيل", "Ceramic coating", "حماية أفلام", "بكج VIP"],
    seed_categories: ["غسيل وتلميع", "تفصيل داخلي", "Ceramic", "Wraps", "Detailing شامل"],
    welcome_ar: "عربيتك تستاهل أحسن",
    welcome_en: "Your car deserves the best",
  },

  // ====================== SERVICES (2) ======================
  {
    id: "svc-pro",
    industry: "services",
    name: "خدمات احترافية",
    tagline: "كحلي + رمادي — مكاتب وشركات استشارية",
    emoji: "💼",
    hero: u("photo-1497366216548-37526070297c"),
    palette: { primary: "220 50% 25%", accent: "210 15% 50%", bg: "0 0% 98%", foreground: "220 40% 12%" },
    pos_layout: "classic",
    features: ["فواتير بالساعة", "عروض أسعار", "اشتراكات شهرية", "مراكز تكلفة"],
    seed_categories: ["استشارة", "تصميم", "تنفيذ", "متابعة", "تطوير"],
    welcome_ar: "خبرة تليق بمشروعك",
    welcome_en: "Expertise that delivers",
  },
  {
    id: "svc-creative",
    industry: "services",
    name: "وكالة إبداعية / ميديا",
    tagline: "بنفسجي + برتقالي — للوكالات والمحتوى",
    emoji: "🎨",
    hero: u("photo-1517048676732-d65bc937f952"),
    palette: { primary: "280 65% 45%", accent: "20 95% 60%", bg: "280 15% 97%", foreground: "280 50% 15%" },
    pos_layout: "classic",
    features: ["باقات إنتاج", "متابعة مشاريع", "اشتراكات شهرية"],
    seed_categories: ["تصميم", "تصوير", "Social Media", "إنتاج فيديو", "Branding"],
    welcome_ar: "نخلق قصة لمشروعك",
    welcome_en: "Stories that move",
  },

  // ====================== GYM / FITNESS (2) ======================
  {
    id: "gym-energy",
    industry: "gym",
    name: "جيم حماسي",
    tagline: "أحمر + أسود — طاقة وقوة",
    emoji: "🏋️",
    hero: u("photo-1534438327276-14e5300c3a48"),
    palette: { primary: "0 80% 50%", accent: "0 0% 12%", bg: "0 0% 7%", foreground: "0 0% 95%" },
    pos_layout: "classic",
    features: ["اشتراكات شهرية / سنوية", "حضور بالـ QR", "مدربين شخصيين", "باقات"],
    seed_categories: ["اشتراكات", "مدرب شخصي", "Classes", "مكملات", "ملابس"],
    welcome_ar: "النسخة الأقوى منك تبدأ هنا 💪",
    welcome_en: "Stronger every day",
  },
  {
    id: "gym-yoga",
    industry: "gym",
    name: "يوغا / بيلاتس",
    tagline: "أخضر زيتي + رمل — هدوء وانسجام",
    emoji: "🧘‍♀️",
    hero: u("photo-1545205597-3d9d02c29597"),
    palette: { primary: "130 30% 35%", accent: "30 40% 70%", bg: "60 25% 96%", foreground: "130 35% 12%" },
    pos_layout: "classic",
    features: ["حصص بمواعيد", "اشتراكات Drop-in", "بيع سجاد ومستلزمات"],
    seed_categories: ["حصص يوغا", "بيلاتس", "Meditation", "مستلزمات", "ملابس"],
    welcome_ar: "خد نفسك 🍃",
    welcome_en: "Breathe in, breathe out",
  },
];

export const INDUSTRIES: Array<{ id: BusinessTheme["industry"]; label_ar: string; label_en: string; emoji: string }> = [
  { id: "restaurant",   label_ar: "مطاعم وكافيهات",  label_en: "Restaurants & Cafés",  emoji: "🍽️" },
  { id: "fashion",      label_ar: "أزياء وموضة",     label_en: "Fashion",              emoji: "👗" },
  { id: "supermarket",  label_ar: "سوبرماركت",        label_en: "Supermarket",          emoji: "🛒" },
  { id: "electronics",  label_ar: "إلكترونيات",      label_en: "Electronics",          emoji: "📱" },
  { id: "pharmacy",     label_ar: "صيدليات",          label_en: "Pharmacy",             emoji: "💊" },
  { id: "salon",        label_ar: "صالونات وسبا",     label_en: "Salon & Spa",          emoji: "💇" },
  { id: "auto",         label_ar: "ورش سيارات",       label_en: "Auto Workshop",        emoji: "🚗" },
  { id: "services",     label_ar: "خدمات احترافية",  label_en: "Professional",         emoji: "💼" },
  { id: "gym",          label_ar: "جيم وفتنس",        label_en: "Gym & Fitness",        emoji: "🏋️" },
];
